### ISSUE TITLE
Something special must be made

### ISSUE THREAD

**Issue by kaikaibenkai** [uplanfor/ualgorithm.lua#1]
The functions of table in native `Lua` can simply realize these functions. Therefore, the functions you do must be better than table.
For example, construct a function that **visualizes the container**? Although it is a few difficult, this is a striking bright spot..

**Comment by kaikaibenkai** [comment]
Then, the results of the visualization function can be printed to the console or combined with the UI in miniworld.

**Comment by uplanfor** [comment]
So I abandoned the file `uarray.lua`.

**Comment by uplanfor** [comment]
Thanks for your suggestions!

**Comment by uplanfor** [comment]
completed

**Comment by uplanfor** [comment]
> Then, the results of the visualization function can be printed to the console or combined with the UI in miniworld.

所以给每个类分别实现toString函数即可，这样就可以在控制台显示结果了。谢谢啦！
